- set_fact:
    server_arch: >-
      {%- if ansible_architecture in ["armv8l", "aarch64"] -%}
      arm64
      {%- elif ansible_architecture == "x86_64" -%}
      amd64
      {%- endif -%}
  tags: always

- import_tasks: deps_apt.yml
  tags:
    - hornet_deps_apt
  when:
    - ansible_distribution in debian_family_list
    - install_system_deps|default(False)|bool

- import_tasks: deps_yum.yml
  tags:
    - hornet_deps_yum
  when:
    - ansible_distribution in redhat_family_list
    - install_system_deps|default(False)|bool

- import_tasks: pip.yml
  tags:
    - py_docker

- name: hornet home path
  file:
    state: directory
    mode: 0700
    owner: "{{ hornet_user }}"
    group: "{{ hornet_group }}"
    path: "{{ item }}"
  with_items:
    - "{{ hornet_home_path }}"

- import_tasks: tanglevisualiser.yml
  tags:
    - tanglevisualiser_role

- import_tasks: tanglemonitor.yml
  tags:
    - tanglemonitor_role

- name: set ip variable if not set
  set_fact:
    ip: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"
  when: ip is not defined

- import_tasks: firewalld.yml
  tags:
    - hornet_firewalld
  when:
    - ansible_distribution in redhat_family_list
    - configure_firewall|default(False)|bool

- import_tasks: ufw.yml
  tags:
    - hornet_ufw
  when:
    - ansible_distribution in debian_family_list
    - configure_firewall|default(False)|bool

- import_tasks: hornet.yml
  tags:
    - hornet_config

- import_tasks: ssl.yml
  tags:
    - hornet_ssl
