- name: stop if no systemd support
  assert:
    that: ansible_service_mgr == "systemd"
  tags:
    - always
    - check_service_mgr
  ignore_errors: "{{ ignore_assert_errors }}"

- name: stop if unknown distribution
  assert:
    that: ansible_distribution in debian_family_list or ansible_distribution in redhat_family_list
  tags:
    - always
    - check_dist
  ignore_errors: "{{ ignore_assert_errors }}"

- name: stop if memory is too small
  assert:
    that: ansible_memtotal_mb >= min_required_memtotal_mb
  ignore_errors: "{{ ignore_assert_errors }}"
  tags:
    - always
    - check_memory

- name: stop if architecture is not supported
  assert:
    that: 'ansible_architecture in ["armv8l", "aarch64", "x86_64"]'
  ignore_errors: "{{ ignore_assert_errors }}"
  tags:
    - always
    - check_arch
